### ISSUE TITLE
Überprüfung der englischen Übersetzungen

### ISSUE THREAD

**Issue by TobeSoftwareGmbH** [TobeSoftwareGmbH/EcoClubWebsite#12]
Bitte schau dir nochmal die Übersetzungen an.

Bussi

**Comment by mariosbf** [comment]
"This website has been designed by [...]"

"Has been" würde heißen, dass wir mit der Entwicklung fertig sind. 
Ich würde eher zu "is being designed" oder eher "was designed" tendieren.

**Comment by TobeSoftwareGmbH** [comment]
In der deutschen Version haben wir auch "[...]wurde erstellt von[...]"

aber du hast recht, ich verändere es bei beiden zu "wird erstellt von" und "is being designed"
