### ISSUE TITLE
URLs der Websiten

### ISSUE THREAD

**Issue by TobeSoftwareGmbH** [TobeSoftwareGmbH/EcoClubWebsite#3]
Ich habe die neue EcoWoche-Seite in /pages/EcoWoche geschoben. Welche URL wäre dir als User lieber?

1. URL/pages/EcoWoche   (wäre fürs Coden übersichtlicher)

2. URL/EcoWoche  (würden viele Ordner im main-View auf GitHub sein)

**Comment by mariosbf** [comment]
Ersteres

**Comment by TobeSoftwareGmbH** [comment]
Alles klar Herr Komissar
