### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by mariosbf** [TobeSoftwareGmbH/EcoClubWebsite#8]
Der Footer muss unten festgenagelt werden.

**Comment by TobeSoftwareGmbH** [comment]
Ist getan, jedoch muss dazu bei jeder Seite etwas verändert werden:

```
<div class="page_container">
      <div class="content_wrap">
         //Websitenzeug hier
      </div>
      <footer class="footer"><object class="bottom animated fadeIn" type="text/html" data="html_tools/bottom.html"></object></footer>
</div>
```

Solange _general_style.css_ verlinkt ist, sollte es gehen
Küsschen

**Comment by TobeSoftwareGmbH** [comment]
Progress für das Fixen:

- [ ] Startseite
- [ ] Artikel-Seiten
- [ ] Mitmachen

**Comment by TobeSoftwareGmbH** [comment]
Quelle: https://medium.freecodecamp.org/how-to-keep-your-footer-where-it-belongs-59c6aa05c59c
